root: 'submission/images/'
test_list: 'submission/images_w_boxes.csv'
pairs_list: 'submission/submission_list.csv'
batch_size: 256
augmentations: 'default'
augmentations_valid: 'default'
num_workers: 16

